# Site settings
title: Starfish Spectroscopic Stellar Inference
email: iczekala@cfa.harvard.edu
description: > # this means to ignore newlines until "baseurl:"
  Robust spectroscopic inference
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://iancze.github.io/Starfish" # the base hostname & protocol for your site
twitter_username: iczekala
github_username:  iancze

# Build settings
markdown: kramdown
